### ISSUE TITLE
[EnhanceMent] Support FastAPI

### ISSUE THREAD

**Issue by NullXeronier** [ftrias/jyserver#1]
I want use jyserver library with FastAPi...
Thanks.

**Comment by hasansezertasan** [comment]
I was going to open an issue about it but I see that FastAPI support is already requested. WDYT about this @ftrias?

**Comment by ftrias** [comment]
I've never used FastAPI before, but after playing with it a bit, it is very similar to Flask and Bottle so I added support for it. Please pull the latest changes and let me know what you think.
